apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datanode
spec:
  serviceName: "datanode"
  replicas: 5
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
      - name: datanode
        image: raorizwaniftikhar/hadoop-echo-systems-ki8:latest
        ports:
        - containerPort: 9864  # Web UI
        - containerPort: 9866  # Data Transfer
        - containerPort: 9867  # IPC
        env:
        - name: CLUSTER_NAME
          value: HadoopCluster
        - name: NAMENODE_HOST
          value: namenode-service  # Kubernetes service name
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
            storage: "10Gi"
          limits:
            memory: "1Gi"
            cpu: "1"
            storage: "20Gi"
        volumeMounts:
        - name: datanode-storage
          mountPath: /usr/local/hadoop/data/hdfs/datanode
        tty: true
  volumeClaimTemplates:
  - metadata:
      name: datanode-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
