apiVersion: v1
kind: Service
metadata:
  name: journalnode
  namespace: bigdata
spec:
  clusterIP: None 
  ports:
    - name: rpc
      port: 8485
      targetPort: 8485
    - name: web
      port: 8480
      targetPort: 8480
  selector:
    app: journalnode

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: journalnode
  namespace: bigdata
spec:
  serviceName: "journalnode"
  replicas: 3
  selector:
    matchLabels:
      app: journalnode
  template:
    metadata:
      labels:
        app: journalnode
    spec:
      containers:
      - name: journalnode
        image: raorizwaniftikhar/hadoop-echo-systems-ki8:latest
        ports:
        - containerPort: 8485
        - containerPort: 8480
        volumeMounts:
        - name: journalnode-storage
          mountPath: /hadoop/dfs/journal
  volumeClaimTemplates:
  - metadata:
      name: journalnode-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi