apiVersion: v1
kind: Service
metadata:
  name: resourcemanager
  namespace: bigdata
spec:
  selector:
    app: resourcemanager
  ports:
    - port: 8088  # Web UI
      targetPort: 8088
      name: web
    - port: 8032  # IPC
      targetPort: 8032
      name: ipc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resourcemanager
  namespace: bigdata
  labels:
    app: resourcemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resourcemanager
  template:
    metadata:
      labels:
        app: resourcemanager
        component: resourcemanager
    spec:
      containers:
        - name: resourcemanager
          image: raorizwaniftikhar/hadoop-echo-systems-ki8:latest
          env:
            - name: CLUSTER_NAME
              value: HadoopCluster
            - name: NAMENODE_HOST
              value: namenode-service  # use actual Namenode service name
          ports:
            - containerPort: 8088  # Web UI
            - containerPort: 8032  # IPC
          tty: true
      terminationGracePeriodSeconds: 30
