apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: bigdata
spec:
  selector:
    app: spark-master
  ports:
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 8080
      targetPort: 8080
      name: ui
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: bitnami/spark:latest
          env:
            - name: SPARK_MODE
              value: master
            - name: SPARK_MASTER_URL
              value: spark://spark-master:7077
          ports:
            - containerPort: 7077
            - containerPort: 8080
          tty: true
