apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: bigdata
spec:
  ports:
    - port: 2181
      targetPort: 2181
      nodePort: 32181
  selector:
    app: zookeeper
  type: NodePort
---
# Zookeeper Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          ports:
            - containerPort: 2181
---
# ZooNavigator Service
apiVersion: v1
kind: Service
metadata:
  name: zoonavigator
  namespace: bigdata
spec:
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30900
  selector:
    app: zoonavigator
  type: NodePort
---
# ZooNavigator Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoonavigator
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoonavigator
  template:
    metadata:
      labels:
        app: zoonavigator
    spec:
      containers:
        - name: zoonavigator
          image: elkozmon/zoonavigator
          env:
            - name: CONNECTION_STRING
              value: zookeeper:2181
            - name: HTTP_AUTH_TYPE
              value: basic
            - name: HTTP_AUTH_USER
              value: hadoop
            - name: HTTP_AUTH_PASS
              value: hadoop
          ports:
            - containerPort: 9000